# ------------------------------------------------------ #
#  Makefile     ( MapleBBS - WindTop -DreamBBS )         #
# ------------------------------------------------------ #
#  author : r2.bbs@bbs.ccns.ncku.edu.tw                  #
#  target : Makefile for DreamBBS sample files           #
#  create : 2017/08/10                                   #
#  update : 2017/  /                                     #
# ------------------------------------------------------ #


####### CAUTION: Still Testing!! Don't try it on important sites #######


SBBS =	bbs

SCON =	config.h

#SMAK =	../src        ## not done yet

newbbs:
	cp -r $(SBBS)/* ~/;cp $(SBBS)/.BRD ~/

config:
	cp $(SCON) ../src/include/

#mainmake:            ## not done yet
        
        
