name: Sending workflow dispatch to "imagedreambbs" project

on:
  push:
    branches: [main, develop]

jobs:
  sent-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/bbsdocker/imagedreambbs/dispatches --data '{"event_type": "Receive Source Code Update from Upstream"}'
          echo "Dispatch sent."
