name: Sending workflow dispatch to "imagedreambbs" project

on:
  push:
    branches: [master, develop]

jobs:
  sent-dispatch-job:
    if: ${{ !contains(github.event.head_commit.message, 'skip-ci') }}
    runs-on: ubuntu-latest
    steps:
      - env:
          WORKFLOW_ID: 'push_container.yml'
        run: |
          curl \
            -X POST \
            -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/bbsdocker/imagedreambbs/actions/workflows/$WORKFLOW_ID/dispatches \
            --data '{
            "ref": "refs/heads/master",
            "inputs": {"src_ref": "'"$GITHUB_REF"'", "src_sha": "'"$GITHUB_SHA"'"}
            }'
          echo "Dispatch sent."
